# Generated by Django 4.2.18 on 2025-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='Your signature here', max_length=140)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
